#######################################################################
###                                                                 ###
### WARNING: This file is generated, please update the template at: ###
###            generator/sbpg/targets/resources/sbp2json-cargo.toml ###
###                                                                 ###
#######################################################################

[package]
name = "sbp2json"
version = "(((release)))"
authors = ["Swift Navigation <dev@swiftnav.com>"]
edition = "2018"

[dependencies.sbp]
path = "../sbp"
features = ["json"]

[dependencies]
structopt = "0.3"
env_logger = "0.8"
atty = "0.2"

[target.'cfg(all(not(windows), not(target_env = "musl")))'.dependencies]
jemallocator = "0.3"

[dev-dependencies]
sha2 = "0.8"
hex = "0.4"
assert_cmd = "1.0.1"
serde_json = "1"
assert-json-diff = "1.1.0"

[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = "sbp2json"
path = "src/bin/sbp2json.rs"

[[bin]]
name = "json2sbp"
path = "src/bin/json2sbp.rs"

[[bin]]
name = "json2json"
path = "src/bin/json2json.rs"
